### ISSUE TITLE
See how many episodes it takes for q table to stabilize

### ISSUE THREAD

**Issue by mariemayadi** [AmoghM/Reinforcement-Learning-Trade-Strategies#19]
See parent  umberella comment:
Employ multiple new states (see above!) including those suggested in the meeting & those Kevin drafted up (maybe reducing # of quantiles from 10 to 3-5 will be necessary here to avoid curse of dimensionality)

**Comment by mariemayadi** [comment]
Example moving to a 100. Similar to epochs.

**Comment by mariemayadi** [comment]
Ideas:
- graph
- decide on stability definition

**Comment by shreyasj3006** [comment]
Use the total portfolio value measure to visualize the performance of the episode tuning process which in turn tells us when the q-table has stabilized. @bwliv

**Comment by bwliv** [comment]
Can also measure gradient of Q table and stop when it reaches a certain
value, that might be more stable

**Comment by bwliv** [comment]
This will be added in latest push. @shreyasj3006 @mariemayadi seeing some extreme jumps here and there, making it tough to track stabilization. Might want to track what's causing such extreme jumps; might be that the penalty of 100 in line 264 of trainqlearner_util.py.
