### ISSUE TITLE
Add commission

### ISSUE THREAD

**Issue by mariemayadi** [AmoghM/Reinforcement-Learning-Trade-Strategies#22]
Commission - charge $2 for every buy and sell both in training and testing, see if it leads to more holding (it should!)

**Comment by bwliv** [comment]
added commission parameter to train_q_learner - subtracts flat-rate commission from reward every time a buy or sell action is taken; this is added to the hyperparameters that serve as arguments in the function (will show up in my next PR)

**Comment by bwliv** [comment]
made $2 by default per request from mentors and @mariemayadi
