### ISSUE TITLE
State Transition

### ISSUE THREAD

**Issue by mariemayadi** [AmoghM/Reinforcement-Learning-Trade-Strategies#24]
Comment received was to add a time domain to further explain the black box in an easy verbal manner. Markov is an option but not necessarily. Consider looking at Yahoo Finance way of 'adding value of indicator' along existing line graph

aka visualization for state transition matrix

**Comment by mariemayadi** [comment]
Question: training or testing?

**Comment by bwliv** [comment]
added state transition matrices for testing (will show up in my next PR)

**Comment by bwliv** [comment]
used markov transition tables - row is current state, and each column within the row defines the empirical probability of the next state (based on that current state) based on testing
