### ISSUE TITLE
Making the hyperparameters variables

### ISSUE THREAD

**Issue by mariemayadi** [AmoghM/Reinforcement-Learning-Trade-Strategies#29]
We should be able to tune hyperparameters directly from the function in some sort of non-intensive way

**Comment by mariemayadi** [comment]
@bwliv for further edits/expension to the description. Thanks

**Comment by mariemayadi** [comment]
@shreyasj3006  and @mariemayadi propose discussing as a team how to integrate - because the current process uses manual graph checking for best hyperparam

**Comment by bwliv** [comment]
I agree with that sentiment - I think we do other to-dos this week then the last step in December is a mix of (1) exploratory DQN and (2) changing code structure to accommodate interaction hyperparameter tuning & generating visualization of those results... easily splittable into two teams

**Comment by bwliv** [comment]
rolling into #27
