### ISSUE TITLE
New Indicator(s) (part 1: raw data to calculating/setting up the indicator)

### ISSUE THREAD

**Issue by mariemayadi** [AmoghM/Reinforcement-Learning-Trade-Strategies#30]
Connecting equation to Yahoo raw input data

**Comment by mariemayadi** [comment]
@kwomackcodes writing a python function for team to call but also open to meeting internally with @shreyasj3006 and @mariemayadi

**Comment by bwliv** [comment]
i created market relative daily return to take care of this - i'll assume this is good enough to be the one (it took a couple hours so i'm not sure adding more states will make the project too much better unless something crazy comes up - we're already up to 64 state dimensions, another state would make it 256 which might be too sparse to evaluate in a three-year period)

if you feel differently @kwomackcodes @mariemayadi @shreyasj3006 feel more than free to reopen this should we like to add another
