### ISSUE TITLE
New Indicator(s) (part 2: add calculated indicator as a State)

### ISSUE THREAD

**Issue by mariemayadi** [AmoghM/Reinforcement-Learning-Trade-Strategies#31]
Successor to Issue #30 

Once the new indicator is calculated, discretize and add the the df and subsequent code as a new State

**Comment by mariemayadi** [comment]
@kwomackcodes we are expecting only **one** indicator, correct? (as per feedback from the Tuesday mentor meeting)

**Comment by bwliv** [comment]
i created market relative daily return to take care of this - i'll assume this is good enough to be the one (it took a couple hours so i'm not sure adding more states will make the project too much better unless something crazy comes up - we're already up to 64 state dimensions, another state would make it 256 which might be too sparse to evaluate in a three-year period)

if you feel differently @kwomackcodes @mariemayadi @shreyasj3006 feel more than free to reopen this should we like to add another
